from losses.KD import *
from losses.SPKD import *
from losses.SingleCCD import *
from losses.CRD import *
from losses.HSAKD import *
from losses.SSKD import *
from losses.SingleDKD import *
from losses.DKDLoss import *
from losses.DISTLoss import *
from losses.PKDLoss import *